const fs=require('fs');const{chromium}=require('C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir='C:/Users/Admin/Desktop/Скрипты/File for github/case_covers_professional_20261002';fs.mkdirSync(dir,{recursive:true});
const iconNames={starter:'buildings',automotive:'car-profile',donate_currency:'currency-circle-dollar',jackpot:'coins',diversity:'stack',contraband:'detective',style:'crown-simple',estate:'house-line',exclusive:'sketch-logo',special_donate:'seal-check'};
const symbols={};for(const[id,name]of Object.entries(iconNames)){const raw=fs.readFileSync(dir+'/source/'+name+'.svg','utf8');symbols[id]=raw.replace(/<svg[^>]*>/,'').replace('</svg>','').replace(/currentColor/g,'black');}
const names={starter:'Начальный',automotive:'Автомобильный',donate_currency:'Донат Валюта',jackpot:'Джекпот',diversity:'Разнообразие',contraband:'Контрабанда',style:'Стиль',estate:'Недвижимость',exclusive:'Эксклюзив',special_donate:'Спец донат'};
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const p=await b.newPage({viewport:{width:512,height:512}});let manifest=[];
for(const[id,rawSymbol]of Object.entries(symbols)){
await p.setContent(`<svg><g id="measure">${rawSymbol}</g></svg>`);
const box=await p.locator('#measure').evaluate(e=>{let b=e.getBBox();return {x:b.x,y:b.y,w:b.width,h:b.height}});
const scale=84/Math.max(box.w,box.h);
const tx=128-(box.x+box.w/2)*scale,ty=161-(box.y+box.h/2)*scale;
const symbol=`<g transform="translate(${tx} ${ty}) scale(${scale})">${rawSymbol}</g>`;

const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 256 256"><defs><mask id="cut"><rect width="256" height="256" fill="white"/><path d="M24 108h208" stroke="black" stroke-width="4"/><g fill="black"><rect x="54" y="94" width="21" height="33" rx="4"/><rect x="181" y="94" width="21" height="33" rx="4"/>${symbol}</g><g fill="white"><path d="M59 99h11v18H59zm127 0h11v18h-11z"/></g></mask></defs><g fill="white" mask="url(#cut)"><path d="M80 83V65q0-5 4-9l10-10q3-3 8-3h52q5 0 8 3l10 10q4 4 4 9v18h-16V66l-7-7h-50l-7 7v17z"/><path d="M51 80h154l9 9h8l10 10v99l-16 16H40l-16-16V99l10-10h8z"/></g></svg>`;
const filename=`case_cover_${id}_v7.png`;fs.writeFileSync(`${dir}/${filename.replace('.png','.svg')}`,svg);await p.setContent(`<style>body{margin:0;background:transparent}</style>${svg}`);await p.screenshot({path:dir+'/'+filename,omitBackground:true});fs.copyFileSync(dir+'/'+filename,'C:/Users/Admin/Desktop/Скрипты/File for github/'+filename);manifest.push({id,name:names[id],filename});}
fs.writeFileSync(dir+'/manifest.json',JSON.stringify(manifest,null,2));await p.setViewportSize({width:1100,height:530});await p.setContent(`<style>body{margin:0;background:#26272e;color:white;font:14px Arial;display:grid;grid-template-columns:repeat(5,1fr);gap:12px;padding:20px;box-sizing:border-box}article{text-align:center;background:#1c1d22;border-radius:12px}img{width:180px;height:180px}p{margin:0 0 20px}</style>${manifest.map(c=>`<article><img src="data:image/png;base64,${fs.readFileSync(dir+'/'+c.filename).toString('base64')}"><p>${c.name}</p></article>`).join('')}`);await p.screenshot({path:dir+'/preview.png',fullPage:true});await p.setViewportSize({width:1100,height:230});await p.setContent(`<style>body{margin:0;background:#26272e;color:white;font:11px Arial;display:flex;gap:20px;padding:20px}article{text-align:center}img{width:72px;height:72px}</style>${manifest.map(c=>`<article><img src="data:image/png;base64,${fs.readFileSync(dir+'/'+c.filename).toString('base64')}"><p>${c.name}</p></article>`).join('')}`);await p.screenshot({path:dir+'/preview_small.png'});await b.close();console.log('10 approved-style icons saved.');})();

