--[[
	Конфигурация Cases System: 10 официальных сбалансированных кейсов.
	Author: Antigravity Assistant
]]

CasesSystem = CasesSystem or {}
local CS = CasesSystem

CS.Config = CS.Config or {}

CS.Config.Name = "Cases System"
CS.Config.MaxOpenAtOnce = 10
CS.Config.MaxCasesPerRequest = 10
CS.Config.MaxCases = 64
CS.Config.MaxAdminPayload = 60000
CS.Config.MaxRewardDataPayload = 8192
CS.Config.MaxPublicCasesPacket = 30000
CS.Config.MaxAdminCasesPacket = 45000
CS.Config.MaxPublicCasesJSON = 300000
CS.Config.MaxAdminCasesJSON = 800000
CS.Config.AdminPermission = "cases_manage"
CS.Config.AdminDefaultRank = "superadmin"

CS.Config.CatalogVIPRank = "vip"
CS.Config.CatalogJobCommand = "citizen"
CS.Config.EnablePrivilegeCasesByDefault = true
CS.Config.SeedMissingDefaultCases = true
CS.Config.AlwaysUpdateDefaultCases = true

CS.Config.IGSCategory = "Кейсы"
CS.Config.IGSRegistrationRetry = 5
CS.Config.IGSTransactionTimeout = 25
CS.Config.DirectPurchaseEnabled = true

-- Уведомления отключены по запросу
CS.Config.AnnounceWins = false
CS.Config.AnnounceOnlyMarkedRewards = false

CS.Config.RequestCooldown = 0.20

CS.DefaultCases = {
	-- 1. НАЧАЛЬНЫЙ
	{
		id = "starter",
		igs_uid = "cs_starter",
		name = "Начальный",
		description = "Доступный кейс для новичков: игровая валюта, полезные SWEP-предметы и бонус к заработку.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%BE%D0%B9%20%D1%81%D1%82%D0%B0%D1%80%D1%82.png",
		color = {r = 53, g = 135, b = 229, a = 255},
		price = 49,
		enabled = true,
		rewards = {
			{
				id = "starter_money_10k",
				name = "10000 Игровых рублей",
				description = "Зачисляет 10 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 20,
				sell_price = 10,
				data = {amount = 10000},
			},
			{
				id = "starter_money_20k",
				name = "20000 Игровых рублей",
				description = "Зачисляет 20 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 16,
				sell_price = 20,
				data = {amount = 20000},
			},
			{
				id = "starter_money_50k",
				name = "50000 Игровых рублей",
				description = "Зачисляет 50 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 10,
				sell_price = 50,
				data = {amount = 50000},
			},
			{
				id = "starter_salary_10_1h",
				name = "+10% К доходу профессий на 1 час",
				description = "Увеличивает доход зарплаты всех профессий на 10% в течение 1 часа.",
				icon = "icon16/time.png",
				type = "salary_bonus",
				chance = 12,
				sell_price = 29,
				data = {job_command = "*", mode = "percent", value = 10, duration_minutes = 60},
			},
			{
				id = "starter_lockpick",
				name = "Отмычка",
				description = "Постоянная отмычка для взлома дверей и замков.",
				icon = "icon16/wrench.png",
				type = "perm_weapon",
				chance = 10,
				sell_price = 49,
				data = {class = "lockpick"},
			},
			{
				id = "starter_parkour",
				name = "Паркур",
				description = "SWEP паркура для свободного перемещения по крышам и препятствиям.",
				icon = "icon16/user_go.png",
				type = "perm_weapon",
				chance = 10,
				sell_price = 49,
				data = {class = "grub_knuckle"},
			},
			{
				id = "starter_keypad_cracker",
				name = "Взломщик кейпадов",
				description = "Электронный взломщик кейпадов и терминалов.",
				icon = "icon16/calculator.png",
				type = "perm_weapon",
				chance = 8,
				sell_price = 49,
				data = {class = "keypad_cracker"},
			},
			{
				id = "starter_armorkit",
				name = "Арморкит",
				description = "Постоянный комплект бронежилета для восстановления защиты.",
				icon = "icon16/shield.png",
				type = "perm_weapon",
				chance = 4,
				sell_price = 69,
				data = {class = "weapon_armorkit"},
			},
			{
				id = "starter_medkit",
				name = "Аптечка",
				description = "Медицинская аптечка для восстановления здоровья.",
				icon = "icon16/heart.png",
				type = "perm_weapon",
				chance = 4,
				sell_price = 69,
				data = {class = "weapon_medkit"},
			},
			{
				id = "starter_adv_keypad_cracker",
				name = "Улучшенный взломщик кейпадов",
				description = "Ускоренный профессиональный деплой-взломщик кейпадов.",
				icon = "icon16/lightning.png",
				type = "perm_weapon",
				chance = 2.5,
				sell_price = 79,
				data = {class = "weapon_sh_keypadcracker_deploy"},
			},
			{
				id = "starter_deagle",
				name = "Дигл",
				description = "Мощный крупнокалиберный пистолет Desert Eagle навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 1.5,
				sell_price = 119,
				data = {class = "tfa_deagle"},
			},
			{
				id = "starter_dbarrel",
				name = "Двухстволка",
				description = "Убойный двухствольный дробовик ближнего боя навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 1.0,
				sell_price = 129,
				data = {class = "tfa_dbarrel"},
			},
			{
				id = "starter_val",
				name = "Вал",
				description = "Бесшумный специальный автомат АС «Вал» навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 0.6,
				sell_price = 199,
				data = {class = "tfa_val"},
			},
			{
				id = "starter_m416",
				name = "M416",
				description = "Штурмовая тактическая винтовка M416 навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 0.4,
				sell_price = 479,
				data = {class = "tfa_m416"},
			},
		},
	},

	-- 2. АВТОМОБИЛЬНЫЙ
	{
		id = "automotive",
		igs_uid = "cs_automotive",
		name = "Автомобильный",
		description = "Кейс с городскими автомобилями и легендарными спорткарами для Realistic Car Dealer.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%B0%D0%B2%D1%82%D0%BE%D1%81%D0%B0%D0%BB%D0%BE%D0%BD.png",
		color = {r = 230, g = 90, b = 40, a = 255},
		price = 799,
		enabled = true,
		rewards = {
			{
				id = "auto_vaz_2107",
				name = "ВАЗ-2107",
				description = "Классический седан ВАЗ-2107 навсегда в ваш автосалон.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 40,
				sell_price = 249,
				data = {class = "sim_fphys_vaz_2107", name = "ВАЗ-2107"},
			},
			{
				id = "auto_solaris",
				name = "Hyundai Solaris",
				description = "Надёжный городской автомобиль Hyundai Solaris навсегда в ваш гараж.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 30,
				sell_price = 449,
				data = {class = "sim_fphys_hyu_solaris", name = "Hyundai Solaris"},
			},
			{
				id = "auto_golf_gti",
				name = "Volkswagen Golf GTI Mk.VII",
				description = "Динамичный немецкий хэтчбек Golf GTI Mk.VII навсегда.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 17,
				sell_price = 799,
				data = {class = "sim_fphys_vw_golf_gti14", name = "Volkswagen Golf GTI Mk.VII"},
			},
			{
				id = "auto_mark2",
				name = "Toyota Mark II tourer V",
				description = "Легендарный японский заднеприводный седан Mark II tourer V навсегда.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 8,
				sell_price = 999,
				data = {class = "sim_fphys_toy_mark2", name = "Toyota Mark II tourer V"},
			},
			{
				id = "auto_skyline_r34",
				name = "Nissan Skyline GT-R R34",
				description = "Культовый японский спорткар Nissan Skyline GT-R R34 навсегда.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 4,
				sell_price = 1499,
				data = {class = "sim_fphys_nis_sky_r34", name = "Nissan Skyline GT-R R34"},
			},
			{
				id = "auto_bmw_750li",
				name = "BMW 750Li",
				description = "Премиальный представительский седан BMW 750Li навсегда.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 1,
				sell_price = 2999,
				data = {class = "sim_fphys_bmw_750li", name = "BMW 750Li"},
			},
		},
	},

	-- 3. ДОНАТ ВАЛЮТА
	{
		id = "donate_currency",
		igs_uid = "cs_donate_currency",
		name = "Донат Валюта",
		description = "Кейс для быстрого пополнения и умножения донат-баланса IGS.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/Money.png",
		color = {r = 76, g = 175, b = 80, a = 255},
		price = 199,
		enabled = true,
		rewards = {
			{
				id = "donate_curr_10",
				name = "10 рублей",
				description = "Зачисляет 10 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 30,
				sell_price = 10,
				data = {amount = 10},
			},
			{
				id = "donate_curr_100",
				name = "100 рублей",
				description = "Зачисляет 100 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 28,
				sell_price = 100,
				data = {amount = 100},
			},
			{
				id = "donate_curr_160",
				name = "160 рублей",
				description = "Зачисляет 160 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 20,
				sell_price = 160,
				data = {amount = 160},
			},
			{
				id = "donate_curr_230",
				name = "230 рублей",
				description = "Зачисляет 230 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 12,
				sell_price = 230,
				data = {amount = 230},
			},
			{
				id = "donate_curr_300",
				name = "300 рублей",
				description = "Зачисляет 300 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 5.5,
				sell_price = 300,
				data = {amount = 300},
			},
			{
				id = "donate_curr_600",
				name = "600 рублей",
				description = "Зачисляет 600 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 3.0,
				sell_price = 600,
				data = {amount = 600},
			},
			{
				id = "donate_curr_1000",
				name = "1000 рублей",
				description = "Зачисляет 1 000 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 1.2,
				sell_price = 1000,
				data = {amount = 1000},
			},
			{
				id = "donate_curr_2000",
				name = "2000 рублей",
				description = "Зачисляет 2 000 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 0.3,
				sell_price = 2000,
				data = {amount = 2000},
			},
		},
	},

	-- 4. ДЖЕКПОТ
	{
		id = "jackpot",
		igs_uid = "cs_jackpot",
		name = "Джекпот",
		description = "Азартный кейс с шансом выиграть супер-джекпот до 7777 рублей!",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%B4%D0%B6%D0%B5%D0%BA%D0%BF%D0%BE%D1%82.png",
		color = {r = 255, g = 180, b = 0, a = 255},
		price = 259,
		enabled = true,
		rewards = {
			{
				id = "jackpot_rub_15",
				name = "15 рублей",
				description = "Зачисляет 15 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 35,
				sell_price = 15,
				data = {amount = 15},
			},
			{
				id = "jackpot_rub_35",
				name = "35 рублей",
				description = "Зачисляет 35 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 25,
				sell_price = 35,
				data = {amount = 35},
			},
			{
				id = "jackpot_money_50k",
				name = "50000 Игровых рублей",
				description = "Зачисляет 50 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 18,
				sell_price = 50,
				data = {amount = 50000},
			},
			{
				id = "jackpot_money_100k",
				name = "100000 Игровых рублей",
				description = "Зачисляет 100 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 12,
				sell_price = 80,
				data = {amount = 100000},
			},
			{
				id = "jackpot_rub_300",
				name = "300 рублей",
				description = "Зачисляет 300 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 5.0,
				sell_price = 300,
				data = {amount = 300},
			},
			{
				id = "jackpot_rub_500",
				name = "500 рублей",
				description = "Зачисляет 500 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 3.0,
				sell_price = 500,
				data = {amount = 500},
			},
			{
				id = "jackpot_rub_1500",
				name = "1500 рублей",
				description = "Зачисляет 1 500 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 1.3,
				sell_price = 1500,
				data = {amount = 1500},
			},
			{
				id = "jackpot_rub_3000",
				name = "3000 рублей",
				description = "Крупный выигрыш: зачисляет 3 000 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 0.6,
				sell_price = 3000,
				data = {amount = 3000},
			},
			{
				id = "jackpot_rub_7777",
				name = "7777 рублей",
				description = "ЛЕГЕНДАРНЫЙ СУПЕР-ДЖЕКПОТ: 7 777 рублей на баланс!",
				icon = "icon16/star.png",
				type = "donate_currency",
				chance = 0.1,
				sell_price = 7777,
				data = {amount = 7777},
			},
		},
	},

	-- 5. РАЗНООБРАЗИЕ
	{
		id = "diversity",
		igs_uid = "cs_diversity",
		name = "Разнообразие",
		description = "Сбалансированный кейс с бонусами к пополнению, скидками F4 и оружием.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%A3%D0%BB%D0%B8%D1%87%D0%BD%D1%8B%D0%B9%20%D0%BA%D0%B5%D0%B9%D1%81.png",
		color = {r = 156, g = 39, b = 176, a = 255},
		price = 199,
		enabled = true,
		rewards = {
			{
				id = "div_money_100k",
				name = "100000 Игровых рублей",
				description = "Зачисляет 100 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 25,
				sell_price = 80,
				data = {amount = 100000},
			},
			{
				id = "div_rub_100",
				name = "100 рублей",
				description = "Зачисляет 100 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 22,
				sell_price = 100,
				data = {amount = 100},
			},
			{
				id = "div_topup_10",
				name = "+10% При следующем пополнении донат счета",
				description = "Одноразовый купон на +10% к следующему платежу в IGS.",
				icon = "icon16/money_add.png",
				type = "topup_bonus",
				chance = 15,
				sell_price = 149,
				data = {percent = 10, min_amount = 0, max_bonus = 100000, uses = 1, duration_minutes = 0},
			},
			{
				id = "div_salary_10_8h",
				name = "+10% К доходу профессий на 8 часов",
				description = "Увеличивает доход зарплаты всех профессий на 10% в течение 8 часов.",
				icon = "icon16/time.png",
				type = "salary_bonus",
				chance = 14,
				sell_price = 159,
				data = {job_command = "*", mode = "percent", value = 10, duration_minutes = 480},
			},
			{
				id = "div_rub_160",
				name = "160 рублей",
				description = "Зачисляет 160 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 10,
				sell_price = 160,
				data = {amount = 160},
			},
			{
				id = "div_val",
				name = "Вал",
				description = "Бесшумный специальный автомат АС «Вал» навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 5,
				sell_price = 199,
				data = {class = "tfa_val"},
			},
			{
				id = "div_money_200k",
				name = "200000 Игровых рублей",
				description = "Зачисляет 200 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 4,
				sell_price = 200,
				data = {amount = 200000},
			},
			{
				id = "div_rub_230",
				name = "230 рублей",
				description = "Зачисляет 230 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 3,
				sell_price = 230,
				data = {amount = 230},
			},
			{
				id = "div_f4_discount_50",
				name = "Скидки на покупку любых предметов из f4 50%",
				description = "Постоянная скидка 50% на покупку энтити, патронов и оружия в меню F4.",
				icon = "icon16/tag_blue.png",
				type = "f4_discount_50",
				chance = 1.5,
				sell_price = 239,
				data = {},
			},
			{
				id = "div_m416",
				name = "M416",
				description = "Штурмовая тактическая винтовка M416 навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 0.5,
				sell_price = 479,
				data = {class = "tfa_m416"},
			},
		},
	},

	-- 6. КОНТРАБАНДА
	{
		id = "contraband",
		igs_uid = "cs_contraband",
		name = "Контрабанда",
		description = "Специальное тактическое снаряжение, маскировка и боевой перк инвиза.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%9A%D0%BE%D0%BD%D1%82.png",
		color = {r = 211, g = 47, b = 47, a = 255},
		price = 499,
		enabled = true,
		rewards = {
			{
				id = "contra_car_lockpick",
				name = "Отмычка",
				description = "Постоянная отмычка для взлома дверей и замков.",
				icon = "icon16/key.png",
				type = "perm_weapon",
				chance = 45,
				sell_price = 199,
				data = {class = "lockpick"},
			},
			{
				id = "contra_defib",
				name = "Дефибриллятор навсегда",
				description = "Медицинский дефибриллятор для реанимации товарищей.",
				icon = "icon16/heart_add.png",
				type = "perm_weapon",
				chance = 36,
				sell_price = 299,
				data = {class = "weapon_defibrillator"},
			},
			{
				id = "contra_m416",
				name = "M416",
				description = "Штурмовая тактическая винтовка M416 навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 10,
				sell_price = 479,
				data = {class = "tfa_m416"},
			},
			{
				id = "contra_disguise",
				name = "Чемодан маскировки навсегда",
				description = "Специальный шпионский чемодан маскировки под другие профессии.",
				icon = "icon16/briefcase.png",
				type = "perm_weapon",
				chance = 5,
				sell_price = 499,
				data = {class = "swep_disguise_briefcase"},
			},
			{
				id = "contra_gov_badge",
				name = "Служебное удо",
				description = "Служебное удостоверение сотрудника госструктур навсегда.",
				icon = "icon16/vcard.png",
				type = "perm_weapon",
				chance = 3,
				sell_price = 599,
				data = {class = "weapon_gov_badge"},
			},
			{
				id = "contra_camo_invis",
				name = "Перк «Маскировочный инвиз на 15 сек (КД 3 мин)»",
				description = "Боевой перк Арены: тактическая невидимость на 15 секунд с перезарядкой 3 минуты.",
				icon = "icon16/eye.png",
				type = "arena_perk",
				chance = 1,
				sell_price = 899,
				data = {perk_id = "perk_camo_invis"},
			},
		},
	},

	-- 7. СТИЛЬ
	{
		id = "style",
		igs_uid = "cs_style",
		name = "Стиль",
		description = "Визуальная кастомизация: цветной ник, префикс, неоновые эффекты в TAB и трейлы.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%B2%D0%B8%D0%BF-%D0%BA%D0%BB%D1%83%D0%B1.png",
		color = {r = 0, g = 188, b = 212, a = 255},
		price = 129,
		enabled = true,
		rewards = {
			{
				id = "style_money_25k",
				name = "25000 Игровых рублей",
				description = "Зачисляет 25 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 25,
				sell_price = 25,
				data = {amount = 25000},
			},
			{
				id = "style_rub_30",
				name = "30 рублей",
				description = "Зачисляет 30 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 24,
				sell_price = 30,
				data = {amount = 30},
			},
			{
				id = "style_prefix_reward",
				name = "Префикс в чат на выбор",
				description = "Возможность устанавливать персональный префикс перед ником в чате навсегда.",
				icon = "icon16/comment.png",
				type = "style_prefix",
				chance = 18,
				sell_price = 69,
				data = {},
			},
			{
				id = "style_physgun_reward",
				name = "Кастомный цвет физгана и тулгана",
				description = "Персональный яркий цвет луча физгана и тулгана навсегда.",
				icon = "icon16/color_wheel.png",
				type = "style_physgun",
				chance = 14,
				sell_price = 89,
				data = {},
			},
			{
				id = "style_colored_nick_reward",
				name = "Цветной ник в чате",
				description = "Выделяющийся цветной ник в общем чате навсегда.",
				icon = "icon16/palette.png",
				type = "style_colored_nick",
				chance = 9,
				sell_price = 119,
				data = {},
			},
			{
				id = "style_neon_tab_reward",
				name = "Неоновый ник в TAB",
				description = "Стильное неоновое свечение вашей строки в таблице игроков (Scoreboard).",
				icon = "icon16/wand.png",
				type = "style_neon_tab",
				chance = 5,
				sell_price = 149,
				data = {},
			},
			{
				id = "style_trail_reward",
				name = "Трейл (эффект следов за персонажем)",
				description = "Красивый лазерный эффект шлейфа, тянущийся за вашим персонажем при беге.",
				icon = "icon16/weather_sun.png",
				type = "style_trail",
				chance = 3.5,
				sell_price = 179,
				data = {},
			},
			{
				id = "style_killsound_reward",
				name = "Звук убийства (Kill sound)",
				description = "Кастомный звуковой эффект при каждом совершённом вами убийстве.",
				icon = "icon16/sound.png",
				type = "style_killsound",
				chance = 1.5,
				sell_price = 199,
				data = {},
			},
		},
	},

	-- 8. НЕДВИЖИМОСТЬ
	{
		id = "estate",
		igs_uid = "cs_estate",
		name = "Недвижимость",
		description = "Кейс строителя и домовладельца: лимиты пропов, автозакрытие, скидки и уникальные перки дверей.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%BC%D1%8D%D1%80%D0%B8%D1%8F.png",
		color = {r = 63, g = 81, b = 181, a = 255},
		price = 499,
		enabled = true,
		rewards = {
			{
				id = "estate_money_50k",
				name = "50000 Игровых рублей",
				description = "Зачисляет 50 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 24,
				sell_price = 50,
				data = {amount = 50000},
			},
			{
				id = "estate_rub_75",
				name = "75 рублей",
				description = "Зачисляет 75 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 20,
				sell_price = 75,
				data = {amount = 75},
			},
			{
				id = "estate_money_100k",
				name = "100000 Игровых рублей",
				description = "Зачисляет 100 000 в кошелёк DarkRP.",
				icon = "icon16/money.png",
				type = "darkrp_money",
				chance = 18,
				sell_price = 80,
				data = {amount = 100000},
			},
			{
				id = "estate_rub_150",
				name = "150 рублей",
				description = "Зачисляет 150 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 14,
				sell_price = 150,
				data = {amount = 150},
			},
			{
				id = "estate_prop_25",
				name = "+25 к лимиту пропов навсегда",
				description = "Постоянное расширение лимита спавна пропов на +25 штук.",
				icon = "icon16/brick.png",
				type = "prop_limit_bonus",
				chance = 8,
				sell_price = 199,
				data = {bonus = 25},
			},
			{
				id = "estate_door_discount_50",
				name = "Скидка 50% на аренду дверей",
				description = "Уникальный перк: скидка 50% на покупку и аренду любых дверей навсегда.",
				icon = "icon16/door_in.png",
				type = "unique_door_perk",
				chance = 6,
				sell_price = 249,
				data = {perk_id = "door_discount_50"},
			},
			{
				id = "estate_prop_50",
				name = "+50 к лимиту пропов навсегда",
				description = "Постоянное расширение лимита спавна пропов на +50 штук.",
				icon = "icon16/brick.png",
				type = "prop_limit_bonus",
				chance = 4,
				sell_price = 349,
				data = {bonus = 50},
			},
			{
				id = "estate_door_autoclose",
				name = "Автозакрытие дверей с настройкой в меню навсегда",
				description = "Автоматическое закрытие всех открытых вами дверей через 4 секунды навсегда.",
				icon = "icon16/lock.png",
				type = "door_autoclose",
				chance = 2.5,
				sell_price = 499,
				data = {},
			},
			{
				id = "estate_prop_100",
				name = "+100 к лимиту пропов навсегда",
				description = "Постоянное расширение лимита спавна пропов на +100 штук.",
				icon = "icon16/brick.png",
				type = "prop_limit_bonus",
				chance = 1.8,
				sell_price = 699,
				data = {bonus = 100},
			},
			{
				id = "estate_door_free",
				name = "Бесплатная аренда любых дверей навсегда",
				description = "Уникальный перк: бесплатная аренда любых дверей на сервере навсегда.",
				icon = "icon16/key.png",
				type = "unique_door_perk",
				chance = 1.0,
				sell_price = 799,
				data = {perk_id = "door_free"},
			},
			{
				id = "estate_prop_200",
				name = "+200 к лимиту пропов навсегда",
				description = "Постоянное расширение лимита спавна пропов на +200 штук.",
				icon = "icon16/brick.png",
				type = "prop_limit_bonus",
				chance = 0.5,
				sell_price = 1199,
				data = {bonus = 200},
			},
			{
				id = "estate_car_discount_25",
				name = "Скидка 25% на покупку машин в автосалоне",
				description = "Постоянная скидка 25% на покупку любого автомобиля в автосалоне (суммируется до 50% при втором выпадении).",
				icon = "icon16/car.png",
				type = "cardealer_discount_25",
				chance = 0.2,
				sell_price = 1799,
				data = {},
			},
		},
	},

	-- 9. ЭКСКЛЮЗИВ
	{
		id = "exclusive",
		igs_uid = "cs_exclusive",
		name = "Эксклюзив",
		description = "Элитный кейс с гиперкарами (Lamborghini SIAN, Delorean DMC-12), катаной и мощным арсеналом.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%BE%D0%BB%D0%B8%D0%B3%D0%B0%D1%80%D1%85.png",
		color = {r = 255, g = 112, b = 67, a = 255},
		price = 1999,
		enabled = true,
		rewards = {
			{
				id = "excl_rub_800",
				name = "800 рублей",
				description = "Зачисляет 800 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 28,
				sell_price = 800,
				data = {amount = 800},
			},
			{
				id = "excl_sandbox_parkour",
				name = "Бесконечный паркур",
				description = "Продвинутый бесконечный паркур для молниеносных трюков и прыжков без усталости.",
				icon = "icon16/user_go.png",
				type = "perm_weapon",
				chance = 22,
				sell_price = 999,
				data = {class = "sandbox_knuckle"},
			},
			{
				id = "excl_rub_1000",
				name = "1000 рублей",
				description = "Зачисляет 1 000 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 18,
				sell_price = 1000,
				data = {amount = 1000},
			},
			{
				id = "excl_rub_1200",
				name = "1200 рублей",
				description = "Зачисляет 1 200 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 12,
				sell_price = 1200,
				data = {amount = 1200},
			},
			{
				id = "excl_salary_200_14d",
				name = "+200% К доходу профессий на 14 дней",
				description = "Утроенный доход зарплаты (+200%) на 14 дней для всех профессий!",
				icon = "icon16/time.png",
				type = "salary_bonus",
				chance = 8,
				sell_price = 1799,
				data = {job_command = "*", mode = "percent", value = 200, duration_minutes = 20160},
			},
			{
				id = "excl_desperado",
				name = "tfa_cso_desperado",
				description = "Парные крупнокалиберные револьверы Desperado навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 4.5,
				sell_price = 1999,
				data = {class = "tfa_cso_desperado"},
			},
			{
				id = "excl_rub_2000",
				name = "2000 рублей",
				description = "Зачисляет 2 000 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 3.5,
				sell_price = 2000,
				data = {amount = 2000},
			},
			{
				id = "excl_elvenranger",
				name = "tfa_cso_elvenranger",
				description = "Элитная футуристическая снайперская винтовка Elven Ranger навсегда.",
				icon = "icon16/gun.png",
				type = "perm_weapon",
				chance = 2.0,
				sell_price = 2199,
				data = {class = "tfa_cso_elvenranger"},
			},
			{
				id = "excl_katana",
				name = "Катана",
				description = "Острейшая боевая японская катана навсегда.",
				icon = "icon16/shield.png",
				type = "perm_weapon",
				chance = 1.0,
				sell_price = 2499,
				data = {class = "tfa_l4d2_kfkat"},
			},
			{
				id = "excl_bmw_m5",
				name = "BMW M5 Competition",
				description = "Заряженный спортивный седан BMW M5 Competition (2021) навсегда в автосалон.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 0.5,
				sell_price = 7999,
				data = {class = "sim_fphys_bmw_m5_comp_21", name = "BMW M5 Competition"},
			},
			{
				id = "excl_delorean",
				name = "Delorean DMC-12 BTTF",
				description = "Легендарная машина времени Delorean DMC-12 BTTF навсегда в ваш гараж.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 0.3,
				sell_price = 9999,
				data = {class = "sim_fphys_delorean_dmc12_bttf", name = "Delorean DMC-12 BTTF"},
			},
			{
				id = "excl_lam_sian",
				name = "Lamborghini SIAN FKP 37",
				description = "Эксклюзивный гиперкар Lamborghini SIAN FKP 37 навсегда в ваш гараж.",
				icon = "icon16/car.png",
				type = "rcd_vehicle",
				chance = 0.2,
				sell_price = 14999,
				data = {class = "sim_fphys_lam_sian", name = "Lamborghini SIAN FKP 37"},
			},
		},
	},

	-- 10. СПЕЦ ДОНАТ
	{
		id = "special_donate",
		igs_uid = "cs_special_donate",
		name = "Спец донат",
		description = "Высший донат-кейс сервера с шансом выбить высшие группы привилегий Qmenu и ProjectTeam.",
		icon = "https://raw.githubusercontent.com/Linan5454/GoodAstRP/main/%D0%B2%D0%B8%D0%BF%20%D0%BA%D0%B5%D0%B9%D1%81%D0%BE%D0%B2.png",
		color = {r = 233, g = 30, b = 99, a = 255},
		price = 7999,
		enabled = true,
		rewards = {
			{
				id = "spec_rub_1000",
				name = "1000 рублей",
				description = "Гарантированная компенсация: зачисляет 1 000 рублей на счёт IGS.",
				icon = "icon16/coins.png",
				type = "donate_currency",
				chance = 99.80,
				sell_price = 1000,
				data = {amount = 1000},
			},
			{
				id = "spec_qmenu",
				name = "Qmenu",
				description = "Эксклюзивная группа Qmenu с доступом к спавн-меню и расширенным правам.",
				icon = "icon16/award_star_gold_2.png",
				type = "sam_rank",
				chance = 0.15,
				sell_price = 4999,
				data = {rank = "Qmenu", duration_minutes = 0, allow_replace = true},
			},
			{
				id = "spec_project_team",
				name = "ProjectTeam",
				description = "ВЫСШАЯ ПРИВИЛЕГИЯ СЕРВЕРА: Доступ в закрытую команду руководства ProjectTeam навсегда!",
				icon = "icon16/award_star_gold_3.png",
				type = "sam_rank",
				chance = 0.05,
				sell_price = 6999,
				data = {rank = "ProjectTeam", duration_minutes = 0, allow_replace = true},
			},
		},
	},
}
