from pathlib import Path
import json,html
root=Path(r'C:\Users\Admin\Desktop\Скрипты\File for github\update_20260929')
perks=[('arena_jump_3_v2','Тройной прыжок','ПРОБЕЛ x3','#a855f7'),('arena_dash_v2','Воздушный рывок','SHIFT','#f97316'),('arena_blink_v2','Блинк','R','#f59e0b'),('arena_phase_v2','Фазовый сдвиг','ALT','#06b6d4'),('arena_overdrive_v2','Овердрайв','E + R','#ef4444'),('arena_camo_v2','Маскировка','E + ALT','#8b5cf6'),('arena_mark_500_v2','Клеймо 500-го','E + ПРОБЕЛ','#ffd700')]
hints={'arena_jump_3_v2':'В воздухе','arena_dash_v2':'В прыжке','arena_blink_v2':'В прыжке','arena_phase_v2':'Неуязвимость','arena_overdrive_v2':'+40% силы','arena_camo_v2':'Инвиз 15 сек','arena_mark_500_v2':'+50 HP вспышка'}
css='''*{box-sizing:border-box}body{margin:0;background:#17191f;color:#eceef6;font-family:Segoe UI,Arial,sans-serif;padding:36px}h1{font-size:22px;margin:0 0 8px}p{color:#959bac}button{font:inherit;color:inherit;background:#292d39;border:1px solid #464b5d;padding:10px 16px;border-radius:6px;cursor:pointer}.hud{position:relative;height:250px;margin:24px 0;background:radial-gradient(ellipse at 50% 100%,#2e3238,#1e2229);border:1px solid #353946;border-radius:8px;overflow:hidden}.row{position:absolute;bottom:14px;width:100%;display:flex;justify-content:center;gap:0}.perk{width:126px;position:relative;height:115px;text-align:center}.diamond{position:absolute;top:0;left:23px;width:80px;height:80px;clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%);background:var(--accent)}.inner{position:absolute;inset:1px;clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%);background:#26272e}.core{position:absolute;inset:5px;clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%);background:#17181e}.icon{position:absolute;width:45px;height:45px;left:17.5px;top:12.5px;object-fit:contain}.key{position:absolute;top:68px;left:50%;transform:translateX(-50%);white-space:nowrap;background:#181920;border:1px solid var(--accent);border-radius:3px;height:26px;padding:5px 9px;font-size:11px;font-weight:700}.name{position:absolute;top:100px;left:0;width:126px;font-size:10px;color:#aaadb8;white-space:nowrap}.hint{position:absolute;top:114px;left:0;width:126px;font-size:9px;color:#818796;white-space:nowrap}.timer{display:none;position:absolute;top:46px;left:0;width:80px;text-align:center;font-size:14px;font-weight:700;color:#f5c162;text-shadow:1px 1px 1px #121319}.cooldown .icon{opacity:.45}.cooldown .timer{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:12px}.asset{padding:14px 8px;background:#26272e;border:1px solid #30323b;border-radius:8px;text-align:center;font-size:11px;color:#abb2c7}.asset img{display:block;width:84px;height:84px;object-fit:contain;margin:0 auto 10px}@media(max-width:900px){.row{transform:scale(.75);transform-origin:bottom center;width:133.333%;left:-16.666%}}'''
page='<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoodAstRP — новые иконки и HUD</title><style>'+css+'</style><h1>GoodAstRP · Перки и предметы кейсов</h1><p>Предпросмотр новой компоновки HUD. Это макет; проверка внутри Garry’s Mod нужна отдельно.</p><button onclick="document.querySelector(\'.hud\').classList.toggle(\'cooldown\')">Готовность / перезарядка</button><div class="hud"><div class="row">'
for file,name,key,color in perks:
    page+=f'<div class="perk" style="--accent:{color}"><div class="diamond"><div class="inner"><div class="core"></div></div><img class="icon" src="../{file}.png"><span class="timer">24с</span></div><div class="key">{key}</div><div class="name">{name}</div><div class="hint">{hints[file]}</div></div>'
page+='</div></div><h1>Новые изображения предметов</h1><div class="grid">'
records=json.loads((root/'reward_manifest.json').read_text(encoding='utf-8'))
seen=set()
for r in records:
    f=r['icon_file']
    if f in seen:continue
    seen.add(f)
    page+=f'<div class="asset"><img src="../{f}" onerror="this.style.opacity=0;this.parentElement.style.opacity=.35"><span>{html.escape(r["name"])}</span></div>'
page+='</div></html>'
(root/'preview.html').write_text(page,encoding='utf-8')
print('Offline preview written')
